language: bash

services:
  - docker

dist: "xenial"

install:
#  - ".ci/install-buildx.sh"
  - "./.ci/install-devtools.sh"

script:
  - "./.ci/bundle.sh"
#  - "./.ci/build.sh"

env:
  global:
    - export DOCKER_BUILDKIT=1
